### ISSUE TITLE
Unable to open epub files saved by iBooks

### ISSUE THREAD

**Issue by lftur0vich** [user-none/Sigil#49]
Had an epub I'd downloaded through iBooks and wanted to adjust some of the css to create a little whitespace between paragraphs and line heights for better readability. I finally found the iBook files buried deep in the ~/Library/Containers/com.apple.BKAgenService/Data/Documents/iBooks/Books/ directory. While they have an epub extension, they are not. They are identified by the OS as directories and when Sigil attempts to open them it displays the error: Cannot read file <file_name>: file to open is a directory.

So, the question is, can Sigil check for and compensate for this occurrence and just open the directory as an epub file?

It's possible to access the epub/dir contents by right-clicking the file and choosing the Show Package Contents option and editing them in another app (BBEdit), but it's not as convenient.

thx

**Comment by kevinhendricks** [comment]
Hi,

If they are commercial iBooks then they are all DRM'd and so opening them would not help much.

If not DRM'd and they really are a epub internally then if they are a directory, simply zip them up using any one of a number of epub zip helpers that are available for free (see Mobileread for ePubZip 1.0.2.app and similar for Windows).  They are typically drag-and-drop quick.

Better yet, file a bug report with Apple and get them to allow you to actually export an epub properly from iBooks.

Kevin
