### ISSUE TITLE
Eastern Arabic Numerals (Hindi) Show Error on Validation

### ISSUE THREAD

**Issue by a-wal** [user-none/Sigil#54]
On Windows 7, 64-bit, Language Locale- Iraq:
When using Hindi numbers (the Eastrn Arabic Numerals) -this when I choose the Format option in Region and Language to be Arabic ( Iraq)- I get the following error on validation:

Message: The <date> element's value is "‎07/‎02/‎2015" [OF COURSE, ON MY PC I GET NUMERALS IN A DIFFERENT SHAPE] , which is not a valid date format.

When I choose the Format option in Region and Language to be English (United Sates), the error disappears.
![sigil_date_error_ar_1](https://cloud.githubusercontent.com/assets/10895438/6092005/d0f2df58-aed8-11e4-97ad-c15f987c226b.jpg)

How to overcome this?

**Comment by user-none** [comment]
The internalization settings for Qt have set the the date to your specified local. It appears that the epub spec has a specific date format that it must adhere to. I'll have to look to see if I can force the date to a specific format and ignore the locality setting for that field.

**Comment by user-none** [comment]
Should be fixed in b8ee404. It should be writing the numbers without converting them to local format. If this doesn't work then reopen and I'll look into it again.

**Comment by a-wal** [comment]
I am afraid the fix did not work!

**Comment by a-wal** [comment]
SORRY,
It seems to be fixed!
When I authored a new epub, using local date settings, and then validate, no error was shown.
It is only the old epub (before your fix): when I open it with Sigil and validate it, it shows the same error.
Thank you
