### ISSUE TITLE
Row & Paragraph

### ISSUE THREAD

**Issue by Dix78** [user-none/Sigil#58]
When there is a row ( `<hr /> `) it is not possible to add a new paragraph ( `<p> `) using the wysiwyg editor, but I have to go through the code editor. I encountered this issue using sigil 0.8.4 on windows 8.1

**Comment by user-none** [comment]
This is not a support forum. It is only used for development and working on code specifically. This has nothig to do with with an actual bug nor does it indicate any issue with Sigil itself. 

You need to have an understanding of html and css if you're having presentation issues. Finally please see http://sigil-ebook.com/support/ for information about Sigil's user support.
