### ISSUE TITLE
Crash upon saving, error on launching

### ISSUE THREAD

**Issue by afeder** [user-none/Sigil#59]
When I saved an open file, Sigil crashed. When I tried launching Sigil again, I got an error dialog with these details:
```
Error info: /build/buildd/sigil-0.8.2/src/Sigil/Misc/Utility.cpp(414): Throw in function static void Utility::WriteUnicodeTextFile(const QString&, const QString&)
Dynamic exception type: N5boost16exception_detail10clone_implI14CannotOpenFileEE
std::exception::what: std::exception
[P13file_fullpath] = /tmp/Sigil/scratchpad/b9175dcd-be6e-4f00-9227-bb09906e4808/OEBPS/content.opf
[P16file_errorstring] = No such file or directory

Sigil version: 0.8.2
Runtime Qt: 5.3.0
Compiled Qt: 5.3.0
Platform: Linux
```
On closer inspection, my filesystem had gone into read-only mode for some reason. Rebooting solved my inability to start Sigil again. But either way, you may or may not want to handle such cases more gracefully, i.e. allowing the user to evacuate data in memory as opposed to the program crashing.

**Comment by user-none** [comment]
> But either way, you may or may not want to handle such cases more gracefully

If you would like the behavior changed please open a pull request with a patch. Sigil is unable to operate in the environment your machine has put itself in and has responded as such.

**Comment by afeder** [comment]
I was just following the instruction in the error dialog to report the issue. I apologize for bothering - it won't happen again.

**Comment by user-none** [comment]
This wording has been removed from future releases.
