### ISSUE TITLE
[LINUX] Sigil doesn't run on old notebook

### ISSUE THREAD

**Issue by lodgerz** [user-none/Sigil#63]
Hi,
I have an old notebook (CPU: 1GHz - RAM:128MB) with ArchLinux 32-bit.
I tried to run Sigil 0.8.4-1 but it says this error:

$ sigil
Illegal Instruction (core dumped)

it's a problem of old CPU? maybe Sigil needs "sse2" instruction?

$ cat /proc/cpuinfo
processor   : 0
vendor_id   : GenuineIntel
cpu family   : 6
model      : 8
model name   : Pentium III (Coppermine)
stepping   : 10
microcode   : 0x1
cpu MHz      : 994.680
cache size   : 256 KB
fdiv_bug   : no
hlt_bug      : no
f00f_bug   : no
coma_bug   : no
fpu      : yes
fpu_exception   : yes
cpuid level   : 2
wp      : yes
flags      : fpu vme de pse tsc msr pae mce cx8 sep mtrr pge mca cmov pse36 mmx fxsr sse
bogomips   : 1990.25
clflush size   : 32
cache_alignment   : 32
address sizes   : 36 bits physical, 32 bits virtual
power management:

**Comment by user-none** [comment]
SSE2 has been required for years. At least 2009 if not before.

We hope to remove the component that sets this as required for the next major release (0.9.0). There is no ETA on this.
