### ISSUE TITLE
Do you have plan to update this“Sigil User Guide”？

### ISSUE THREAD

**Issue by Mingkeo** [user-none/Sigil#64]
http://web.sigil.googlecode.com/git/index.html
I think it's a good guide for new users and I want to translate it into Chinese.
But it's version is 0.72 ，I wonder if you have the plan to update it recently？

**Comment by user-none** [comment]
That doc has moved to https://github.com/user-none/Sigil/tree/master/docs .

There are no plans to update the doc at this time. if someone wants to contribute changes and updates they can.
