### ISSUE TITLE
"Ctrl-V" shortcut does not work

### ISSUE THREAD

**Issue by JonathanLalou** [user-none/Sigil#66]
Hi,

On Windows 7 and 8, the shortcut "Ctrl-V" for pasting does not work for versions 0.8.4 and 0.8.5.
Yet, pasting is possible through "Edit > Paste".

The shortcut did work on version 0.7.4.

Thanks and regards,

**Comment by user-none** [comment]
Works for me with and without the shortcut in preference set. Is the shortcut set to something else in preferences?

The only other thing I can suggest is deleting Sigil's ini file. There have been issues with the ini when moving between versions. That said I haven't seen that happen since moving to Qt 5.

**Comment by JonathanLalou** [comment]
Hi,

Thanks for your answer.

After checking: 
* by default, the shorcut does not work
* if in the preferences I manually *remove* the shortcut, then it does work :-/
I assume there must be a conflict between Sigil and system-dependant default shortcuts :-/.

Regards,

**Comment by user-none** [comment]
> if in the preferences I manually remove the shortcut, then it does work :-/ I assume there must be a conflict between Sigil and system-dependant default shortcuts :-/.

This does happen on OS X. It worked for a time but after a certain release (I can't remember which one) you were no longer able to change the shortcut in the application itself. My Windows 7 installation hasn't been updated in a while. I only update it before a major release to ensure as little problems as possible with bugfix releases. My guess is the same sort of thing is now happening with Windows.

**Comment by JonathanLalou** [comment]
OK :)
Thx
