### ISSUE TITLE
Error in code view highlighting

### ISSUE THREAD

**Issue by antonig** [user-none/Sigil#67]
The code view  is considering  /*  as a comment start in an html, page so it highlights in green the rest of the page . The pair /* starts a comment only in css...

Not important, just annoying.

I have Sigil 0.8.6 for Win 64.

Antoni 

PS:  In the name of all Catalan language Sigil users I thank you for solving rhe middle dot bug in the spelling checker. That was important for us, not just annoying!

**Comment by user-none** [comment]
This isn't an error. It's for inline CSS highlighting.
