### ISSUE TITLE
PCRE path on case-sensitive file systems

### ISSUE THREAD

**Issue by kjkrum** [user-none/Sigil#69]
I encountered this problem building on Linux, but it would also affect OSX when building on a case-sensitive file system.

Lines 332-337 of src/CMakeLists.txt contain relative paths like `PCRE/SPCRE.cpp`.  They all need to be changed to e.g. `prce/SPCRE.cpp`.

**Comment by user-none** [comment]
Um.... Since everyplace is using it as uppercase, wouldn't it be easier to
just rename the dir to be uppercase?

**Comment by kjkrum** [comment]
Or that.

**Comment by user-none** [comment]
merged pull request for this.
