### ISSUE TITLE
incompatibility with system bs4

### ISSUE THREAD

**Issue by kytvi2p** [user-none/Sigil#70]
I ran into this problem in Debian Linux but I suppose it would be experienced anywhere in which there's a system-wide `bs4` installed. When a system-wide `bs4` is installed, it is loaded instead of the one included with Sigil. Since the one packaged with Sigil has been modified, this doesn't work.

Upon starting Sigil I receive an `Embedded Python Error` window. When I click it away I get a dialog window stating `error in bs4repair repairPrettyPrintXML: -5`. After clicking away this window, I see the first one again. If I keep clicking the error windows away, Sigil will eventually open.

I worked around this locally by renaming `/usr/share/sigil/python3lib/bs4` and then changing the references under `/usr/share/sigil/python3lib/*.py` (and subdirectories) to point to the new name I gave the directory.

**Comment by user-none** [comment]
Python integration and bundled copies is unfinished. It will only load from
the bundled copies once they are all in place and a python runtime is
bundled as well and only use the system versions if built without copies.

**Comment by kevinhendricks** [comment]
To add to what user-none said, the final version of bs4 will be stock (unmodified) and therefore identical to system bs4.  The current master is in a large state of flux and is not ready to be packaged or be used in any production setting as it is pre-alpha at best.

If you are looking for something usable use the Sigil 0.8.x branch with latest commits.

Kevin
