### ISSUE TITLE
Problem on saving

### ISSUE THREAD

**Issue by schwaben-github** [user-none/Sigil#75]
Error info: Cannot save file C:/Users/Administrator/Documents/(...)/(...)/(...)/CCNA_(...).epub: C:\Projects\Sigil-0.8.6\src\Sigil\Exporters\ExportEPUB.cpp(234): Throw in function void __thiscall ExportEPUB::SaveFolderAsEpubToLocation(const class QString &,const class QString &)
Dynamic exception type: class boost::exception_detail::clone_impl<struct CannotWriteFile>
std::exception::what: Unknown exception
[struct file_fullpath *] = C:/Users/Administrator/Documents/(...)/(...)/(...)/CCNA_(...).epub

Sigil version: 0.8.6
Runtime Qt: 5.4.0
Compiled Qt: 5.4.0
Platform: Windows SysInfo ID 128

**Comment by kevinhendricks** [comment]
Do you have actual write permission to that directory and location where you specified to save the epub?  Do you have enough disk space?

Here is the code snippet:

    QFile real_epub(fullfilepath);

    if (!real_epub.open(QFile::WriteOnly | QFile::Truncate)) {
        temp_epub.close();
        boost_throw(CannotWriteFile() << errinfo_file_fullpath(fullfilepath.toStdString()));
    }

It simply tried to open the output file with the full file path provided in the error report (details of which you removed) with write permission.  If it had succeeded the temporary output epub already created would be copied to that location.  But it is returning, saying that it can not open the file with that path for writing.

Please check your permissions and access rights to your destination directory.
